# Copyright 2020-2026 Luke Murphy and Chris Croome
#
# This file is part of the Webarchitects Uncomplicated Firewall (UFW) Ansible role.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Uncomplicated Firewall (UFW) Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Disable ufw
  community.general.ufw:
    state: disabled
  listen: Disable ufw

- name: Enable ufw
  community.general.ufw:
    state: enabled
  listen: Enable ufw

- name: Reload ufw
  community.general.ufw:
    state: reloaded
  listen: Reload ufw

- name: Reset ufw
  community.general.ufw:
    state: reset
  listen: Reset ufw

- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
  listen: Restart ufw
...
